linters:
  stylelint:
    config: 'stylelint.config.js'
files:
    ignore:        
        - 'assets/css/reset.css' 
        - 'LICENSE'
        - '.gitignore'
        - 'README.md'        
fixers:
    enable: true